#!/bin/bash
dbinstance=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i DBINSTANCE | /usr/bin/awk '{print $3}'`
/usr/bin/echo "dbinstance=$dbinstance"
dbhost=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i DBHOST | /usr/bin/awk '{print $3}'`
/usr/bin/echo "dbhost=$dbhost"
dbport=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i DBPORT | /usr/bin/awk '{print $3}'`
/usr/bin/echo "dbport=$dbport"
clientid=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i clientid | /usr/bin/awk '{print $3}'`
/usr/bin/echo "clientid=$clientid"
dbname=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i DBNAME | /usr/bin/awk '{print $3}'`
/usr/bin/echo "dbname=$dbname"
dbuser=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i DBUSER | /usr/bin/awk '{print $3}'`
/usr/bin/echo "dbuser=$dbuser"
dbpass=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i DBPASS | /usr/bin/awk '{print $3}'`
/usr/bin/echo "dbpass=dbpass"
dbtabspace=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i DBTABSPACE | /usr/bin/awk '{print $3}'`
/usr/bin/echo "dbtabspace=$dbtabspace"
idxspace=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i IDXSPACE | /usr/bin/awk '{print $3}'`
/usr/bin/echo "idxspace=$idxspace"
reltype=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i RELTYPE | /usr/bin/awk '{print $3}'`
/usr/bin/echo "reltype=$reltype"
dbschema=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i  DBSCHEMA | /usr/bin/awk '{print $3}'`
/usr/bin/echo "dbschema=$dbschema"
amlroot=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i  AML_ROOT | /usr/bin/awk '{print $3}'`
/usr/bin/echo "amlroot=$amlroot"
tmpspace=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i  TMPSPACE | /usr/bin/awk '{print $3}'`
/usr/bin/echo "tmpspace=$tmpspace"
filepath=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i  FILEPATH | /usr/bin/awk '{print $3}'`
/usr/bin/echo "filepath=$filepath"
installdir=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i  INSTALLDIR | /usr/bin/awk '{print $3}'`
/usr/bin/echo “installdir=$installdir”
backupdir=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i  BACKUPDIR | /usr/bin/awk '{print $3}'`
/usr/bin/echo “backupdir=$backupdir”
cwddir=`/usr/bin/cat /tmp/install.txt |/usr/bin/grep -i  CWDDIR | /usr/bin/awk '{print $3}'`
/usr/bin/echo “cwddir=$cwddir”
